// <auto-generated />
using System;
using AracIhaleDemo01.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AracIhaleDemo01.Migrations
{
    [DbContext(typeof(AracIhaleDemo01Entities))]
    [Migration("20220915192856_mig3")]
    partial class mig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Arac", b =>
                {
                    b.Property<int>("AracID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracFiyat")
                        .HasColumnType("int");

                    b.Property<int>("AracStatuID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Donanim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovdeTipi")
                        .HasColumnType("int");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<string>("KMBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KayitTipID")
                        .HasColumnType("int");

                    b.Property<int>("MarkaId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RenkId")
                        .HasColumnType("int");

                    b.Property<string>("Resim1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Versiyon")
                        .HasColumnType("int");

                    b.Property<int>("VitesTipi")
                        .HasColumnType("int");

                    b.Property<int>("YakitTipi")
                        .HasColumnType("int");

                    b.Property<int>("YilId")
                        .HasColumnType("int");

                    b.HasKey("AracID");

                    b.HasIndex("AracStatuID");

                    b.HasIndex("KayitTipID");

                    b.ToTable("Arac");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.AracDetay", b =>
                {
                    b.Property<int>("AracDetayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrupAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AracDetayID");

                    b.ToTable("AracDetay");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.AracStatu", b =>
                {
                    b.Property<int>("AracStatuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AracStatuAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AracStatuID");

                    b.ToTable("AracStatu");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.EkspertizStatu", b =>
                {
                    b.Property<int>("EkspertizStatuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EkspertizStatuAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EkspertizStatuID");

                    b.ToTable("EkspertizStatu");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.EkspertizSurec", b =>
                {
                    b.Property<int>("EkspertizSurecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EkspertizStatuID")
                        .HasColumnType("int");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EkspertizSurecID");

                    b.HasIndex("EkspertizStatuID");

                    b.ToTable("EkspertizSurec");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Ihale", b =>
                {
                    b.Property<int>("IhaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IhaleAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IhaleStatuID")
                        .HasColumnType("int");

                    b.Property<int>("KayitTipID")
                        .HasColumnType("int");

                    b.Property<string>("SirketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IhaleID");

                    b.HasIndex("IhaleStatuID");

                    b.HasIndex("KayitTipID");

                    b.ToTable("Ihale");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.IhaleFiyat", b =>
                {
                    b.Property<int>("IhaleFiyatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AracID")
                        .HasColumnType("int");

                    b.Property<string>("IhaleBaslangicFiyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinimumAlımFiyat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IhaleFiyatID");

                    b.HasIndex("AracID");

                    b.ToTable("IhaleFiyat");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.IhaleStatu", b =>
                {
                    b.Property<int>("IhaleStatuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IhaleStatuAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IhaleStatuID");

                    b.ToTable("IhaleStatu");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Ilan", b =>
                {
                    b.Property<int>("IlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IlanAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlanBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IlanID");

                    b.ToTable("Ilan");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.KayitTip", b =>
                {
                    b.Property<int>("KayitTipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<string>("KayitTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("KayitTipID");

                    b.ToTable("KayitTip");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Il")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.HasIndex("RolID");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Paket", b =>
                {
                    b.Property<int>("PaketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaketID");

                    b.ToTable("Paket");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolTuru")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolID");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.RolYetkiIliski", b =>
                {
                    b.Property<int>("RolYetkiIliskiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<int>("YetkiID")
                        .HasColumnType("int");

                    b.HasKey("RolYetkiIliskiID");

                    b.HasIndex("RolID");

                    b.HasIndex("YetkiID");

                    b.ToTable("RolYetkiIliski");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Tramer", b =>
                {
                    b.Property<int>("TramerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TramerAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TramerCesitID")
                        .HasColumnType("int");

                    b.Property<string>("TramerTutari")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TramerID");

                    b.HasIndex("TramerCesitID");

                    b.ToTable("Tramer");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.TramerCesit", b =>
                {
                    b.Property<int>("TramerCesitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TramerCesiti")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TramerCesitID");

                    b.ToTable("TramerCesit");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Yetki", b =>
                {
                    b.Property<int>("YetkiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("YetkiAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YetkiID");

                    b.ToTable("Yetki");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Arac", b =>
                {
                    b.HasOne("AracIhaleDemo01.Models.Entities.AracStatu", "AracStatu")
                        .WithMany()
                        .HasForeignKey("AracStatuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AracIhaleDemo01.Models.Entities.KayitTip", "KayitTip")
                        .WithMany()
                        .HasForeignKey("KayitTipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AracStatu");

                    b.Navigation("KayitTip");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.EkspertizSurec", b =>
                {
                    b.HasOne("AracIhaleDemo01.Models.Entities.EkspertizStatu", "EkspertizStatu")
                        .WithMany()
                        .HasForeignKey("EkspertizStatuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkspertizStatu");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Ihale", b =>
                {
                    b.HasOne("AracIhaleDemo01.Models.Entities.IhaleStatu", "IhaleStatu")
                        .WithMany()
                        .HasForeignKey("IhaleStatuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AracIhaleDemo01.Models.Entities.KayitTip", "KayitTip")
                        .WithMany()
                        .HasForeignKey("KayitTipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IhaleStatu");

                    b.Navigation("KayitTip");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.IhaleFiyat", b =>
                {
                    b.HasOne("AracIhaleDemo01.Models.Entities.Arac", "Arac")
                        .WithMany()
                        .HasForeignKey("AracID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Kullanici", b =>
                {
                    b.HasOne("AracIhaleDemo01.Models.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.RolYetkiIliski", b =>
                {
                    b.HasOne("AracIhaleDemo01.Models.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AracIhaleDemo01.Models.Entities.Yetki", "Yetki")
                        .WithMany()
                        .HasForeignKey("YetkiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("AracIhaleDemo01.Models.Entities.Tramer", b =>
                {
                    b.HasOne("AracIhaleDemo01.Models.Entities.TramerCesit", "TramerCesit")
                        .WithMany()
                        .HasForeignKey("TramerCesitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TramerCesit");
                });
#pragma warning restore 612, 618
        }
    }
}
